version: '3.9'

services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    command: server
    entrypoint: hugo
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    networks:
      - mylocal

  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "my_database"

    volumes:
      -  ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - mylocal

  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - mylocal

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - mylocal
    depends_on:
      - geo

  geo:
    build: ./geo
    container_name: geo
    ports:
      - "1234:1234"
    depends_on:
      - db
      - cache
    restart: on-failure
    networks:
      - mylocal
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "1237:1237"
    restart: on-failure
    networks:
      - mylocal
  auth:
    build: ./auth
    container_name: auth
    ports:
      - "1235:1235"
    restart: on-failure
    networks:
      - mylocal

networks:
  mylocal:
    driver: bridge
