version: '3.9'

services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    command: server
    entrypoint: hugo
    volumes:
      - "./hugo:/src"
    ports:
      - ${HUGO_PORT}:${HUGO_PORT}
    networks:
      - mylocal
  db:
    image: postgres:14.4
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      -  ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - mylocal
  cache:
    image: redis:latest
    container_name: cache
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - mylocal
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - ${PORXY_PORT}:${PORXY_PORT}
    restart: on-failure
    networks:
      - mylocal
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - ${USER_PORT}:${USER_PORT}
    restart: on-failure
    networks:
      - mylocal
  auth:
      build: ./auth
      container_name: auth
      ports:
        - ${AUTH_PORT}:${AUTH_PORT}
      restart: on-failure
      networks:
        - mylocal
  geo:
    build: ./geo
    container_name: geo
    ports:
      - ${GEO_PORT}:${GEO_PORT}
    depends_on:
      - db
      - cache
    restart: on-failure
    networks:
      - mylocal
networks:
  mylocal:
    driver: bridge
